# Binary packages contain only files declared by install().
set(CPACK_PACKAGE_NAME "kukri")
set(CPACK_PACKAGE_VENDOR "stilettocode")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Local-only source comments for Git")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/stilettocode/kukri")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_DIRECTORY "${PROJECT_BINARY_DIR}/packages")
string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" KUKRI_PACKAGE_ARCH)
if(KUKRI_PACKAGE_ARCH MATCHES "^(amd64|x86_64)$")
  set(KUKRI_PACKAGE_ARCH "x64")
elseif(KUKRI_PACKAGE_ARCH MATCHES "^(aarch64|arm64)$")
  set(KUKRI_PACKAGE_ARCH "arm64")
endif()
if(WIN32)
  if(NOT MSVC OR NOT KUKRI_STATIC_MSVC_RUNTIME)
    message(WARNING "Portable Windows packaging is validated only with MSVC and KUKRI_STATIC_MSVC_RUNTIME=ON")
  endif()
  set(KUKRI_PACKAGE_OS "windows")
  set(CPACK_GENERATOR "ZIP")
elseif(APPLE)
  set(KUKRI_PACKAGE_OS "macos")
  set(CPACK_GENERATOR "TGZ")
else()
  set(KUKRI_PACKAGE_OS "linux")
  set(CPACK_GENERATOR "TGZ")
endif()
set(CPACK_PACKAGE_FILE_NAME "kukri-${PROJECT_VERSION}-${KUKRI_PACKAGE_OS}-${KUKRI_PACKAGE_ARCH}")
set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "stilettocode")
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "git (>= 1:2.31)")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_PROJECT_CONFIG_FILE "${PROJECT_SOURCE_DIR}/cmake/CPackOptions.cmake")
# Source releases need a separately reviewed allowlist; do not archive the workspace.
set(CPACK_SOURCE_GENERATOR "")
include(CPack)
